### ISSUE TITLE
VRAM Usage relative to n_frames

### ISSUE THREAD

**Issue by DBarker774** [omerbt/TokenFlow#20]
Hi,

I am relatively new to the AI space so apologies if I am missing key information.

I've noticed that I am able to fully process videos that are under a certain number of n_frames.

For example I can successfully process 30 n_frames of a video however the more I increase the n_frames the more VRAM is required. 

Does this process mean that all frames need to be loaded into VRAM, is it true the more frames the more VRAM you require or are there some optimizations needed for longer videos?

**Comment by DBarker774** [comment]
I should note that I have tried to process a video in batches of 30 frames successfully however this introduces inconsistences along with the number of batches.

**Comment by DBarker774** [comment]
Below is an example output of a video cut into 3 batches of 24 frames.
Note the inconsistencies or jumps between batches which are very noticeable. 

Running the full 450 frames of this video results in CUDA out of memory.

https://github.com/omerbt/TokenFlow/assets/27270800/c44581da-62dd-46e8-81ca-6ac2ca4217be

**Comment by rakesh-reddy95** [comment]
Can you show the results after preprocessing?

**Comment by DBarker774** [comment]
> Can you show the results after preprocessing?

As mentioned this was done in batches of 24 frames each to avoid reaching CUDA out of memory when trying to do all frames at once.

Below are the inverted outputs from preprocessing:

https://github.com/omerbt/TokenFlow/assets/27270800/b1909b4e-da2f-49da-8e2e-9aa65b4f5e05

https://github.com/omerbt/TokenFlow/assets/27270800/8e5ca66a-5cc0-4e28-8fdf-cde4661a2c79

https://github.com/omerbt/TokenFlow/assets/27270800/c09d37d2-11e3-49d6-aafc-77eca2fba7d3

I stopped processing the video in batches due to the inconsistencies.

Any insights are greatly appreciated.

**Comment by DBarker774** [comment]
It's worth mentioning that I also tried processing the video using google collab with an A100 40GB and still ran out of memory.

I'm wondering if I am missing something when it comes to processing longer videos.

**Comment by MichalGeyer** [comment]
Hi there! 
Just to make sure -- the inconsistencies in your result come from treating the video as **3 different videos when running our method**. You shouldn't see such inconsistencies if you were run our method on the full video.

In terms of memory, the main bottleneck is the computation of extended attention on the keyframes, which is a massive matrix multiplication. 
I think it can be lightened (at the expense of run time though) by adding more for loops instead of  batch matrix multiplication in this computation :  https://github.com/omerbt/TokenFlow/blob/06f51a0d0c19bef88f0b9b521146b5b849fbfb76/tokenflow_utils.py#L168C13-L168C16
It's currently written such that above 96 frames it loops over the frames to computes the cross-frame attention of each keyframe. Also it loops over the different attention heads. This was designed for our resources, and you can add a loop and loop over the dimension of the attention sequence_length.

For reference, I was able to run the method on 200+ frames using 48G gpu mem.

Hope this helps!

**Comment by DBarker774** [comment]
Closing this as it has largely been answered.
